from navestidlo import Navestidlo
import ico

class ZoznamNavestidiel:
    def __init__(self, parent):
        self.zoznamNav = {    #slovník návestidiel
            #------------------------------------------RADOSINA-----------------------------------------------------------------------------
            1: Navestidlo(ID=1, nazov='R_Se1', usekPred='RAD_Sk', usekZa='RAD_V1', nazovGUI='RAD_zr_do_st_odZ', enumIkon=ico.NavZriadL, dictIkon=ico.dictZriadovacieL,app=parent, comboBox='zriadovacie'),
            2: Navestidlo(ID=2, nazov='R_Se1p', usekPred='RAD_Sk', nazovGUI='RAD_zr_zo_st_odZ', enumIkon=ico.NavZriadP, dictIkon=ico.dictZriadovacieP, app=parent, comboBox='zriadovacie'),
            3: Navestidlo(ID=3, nazov='R_S', usekPred='RAD_ZBE_TU1', usekZa='RAD_Sk', nazovGUI='RAD_S', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, zavisle=46, app=parent, comboBox='vchodove'),
            4: Navestidlo(ID=4, nazov='R_L1', usekPred='RAD_k1', usekZa='RAD_V1', nazovGUI='RAD_L1', enumIkon=ico.NavOdchodP, dictIkon=ico.dictOdchodoveP, zavisle=47, app=parent, comboBox='odchodove'),
            5: Navestidlo(ID=5, nazov='R_L2', usekPred='RAD_k2', usekZa='RAD_V1', nazovGUI='RAD_L2', enumIkon=ico.NavOdchodP, dictIkon=ico.dictOdchodoveP, zavisle=48, app=parent, comboBox='odchodove'),
            6: Navestidlo(ID=6, nazov='R_S_fik', usekPred='RAD_Sk', nazovGUI='RAD_fik_S', enumIkon=ico.FiktP, dictIkon=ico.dictFiktP, zavisle=49, app=parent, comboBox='fiktivne'),
            7: Navestidlo(ID=7, nazov='R_29_fik', usekPred='RAD_ZBE_TU2_2', nazovGUI='RAD_fik_29', enumIkon=ico.FiktP, dictIkon=ico.dictFiktP, app=parent, comboBox='fiktivne'),
            8: Navestidlo(ID=8, nazov='R_19', usekPred='RAD_ZBE_TU1', usekZa='RAD_ZBE_TU2_1', nazovGUI='RAD_ZBE_19', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, app=parent, oddielove=True, TZZ='AB3'),
            9: Navestidlo(ID=9, nazov='R_18', usekPred='RAD_ZBE_TU2_1', usekZa='RAD_ZBE_TU1', nazovGUI='RAD_ZBE_18', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, app=parent, oddielove=True, TZZ='AB3'),
            10: Navestidlo(ID=10, nazov='R_k1_fik', usekPred='RAD_k1', nazovGUI='RAD_k1_fik', enumIkon=ico.NavOdchodL, dictIkon=ico.dictOdchodoveL, zavisle=50, app=parent, comboBox='odchodove'),
            11: Navestidlo(ID=11, nazov='R_k2_fik', usekPred='RAD_k2', nazovGUI='RAD_k2_fik', enumIkon=ico.NavOdchodL, dictIkon=ico.dictOdchodoveL, zavisle=51, app=parent, comboBox='odchodove'),
            #------------------------------------------ZBEHY-----------------------------------------------------------------------------
            12: Navestidlo(ID=12, nazov='Z_L', usekPred='RAD_ZBE_TU4', usekZa='ZBE_Lk', nazovGUI='ZBE_L', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=58, app=parent, comboBox='vchodove'),
            13: Navestidlo(ID=13, nazov='Z_BL', usekPred='LUZ_ZBE_TU1', usekZa='ZBE_BLk', nazovGUI='ZBE_BL', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=59, app=parent, comboBox='vchodove'),
            14: Navestidlo(ID=14, nazov='Z_L_fik', usekPred='ZBE_Lk', nazovGUI='ZBE_fik_L', enumIkon=ico.FiktL, dictIkon=ico.dictFiktL, zavisle=60, app=parent, comboBox='fiktivne'),
            15: Navestidlo(ID=15, nazov='Z_BL_fik', usekPred='ZBE_BLk', nazovGUI='ZBE_fik_BL', enumIkon=ico.FiktL, dictIkon=ico.dictFiktL, zavisle=61, app=parent, comboBox='fiktivne'),
            16: Navestidlo(ID=16, nazov='Z_Se1p', usekPred='ZBE_Lk', nazovGUI='ZBE_zr_zo_st_odR', enumIkon=ico.NavZriadL, dictIkon=ico.dictZriadovacieL, app=parent, comboBox='zriadovacie'),
            17: Navestidlo(ID=17, nazov='Z_Se2p', usekPred='ZBE_BLk', nazovGUI='ZBE_zr_zo_st_odL', enumIkon=ico.NavZriadL, dictIkon=ico.dictZriadovacieL, app=parent, comboBox='zriadovacie'),
            18: Navestidlo(ID=18, nazov='Z_Se1', usekPred='ZBE_Lk', usekZa='ZBE_V1', nazovGUI='ZBE_zr_do_st_odR', enumIkon=ico.NavZriadP, dictIkon=ico.dictZriadovacieP, app=parent, comboBox='zriadovacie'),
            19: Navestidlo(ID=19, nazov='Z_Se2', usekPred='ZBE_BLk', usekZa='ZBE_V2', nazovGUI='ZBE_zr_do_st_odL', enumIkon=ico.NavZriadP, dictIkon=ico.dictZriadovacieP, app=parent, comboBox='zriadovacie'),
            20: Navestidlo(ID=20, nazov='Z_S1', usekPred='ZBE_k1', usekZa='ZBE_V1', nazovGUI='ZBE_S1', enumIkon=ico.NavOdchodL, dictIkon=ico.dictOdchodoveL, zavisle=62, app=parent, comboBox='odchodove'),
            21: Navestidlo(ID=21, nazov='Z_S2', usekPred='ZBE_k2', usekZa='ZBE_V2', nazovGUI='ZBE_S2', enumIkon=ico.NavOdchodL, dictIkon=ico.dictOdchodoveL, zavisle=63, app=parent, comboBox='odchodove'),
            22: Navestidlo(ID=22, nazov='Z_L1', usekPred='ZBE_k1', usekZa='ZBE_V3', nazovGUI='ZBE_L1', enumIkon=ico.NavOdchodP, dictIkon=ico.dictOdchodoveP, zavisle=64, app=parent, comboBox='odchodove'),
            23: Navestidlo(ID=23, nazov='Z_L2', usekPred='ZBE_k2', usekZa='ZBE_V3', nazovGUI='ZBE_L2', enumIkon=ico.NavOdchodP, dictIkon=ico.dictOdchodoveP, zavisle=65, app=parent, comboBox='odchodove'),
            24: Navestidlo(ID=24, nazov='Z_Se3', usekPred='ZBE_Sk', usekZa='ZBE_V3', nazovGUI='ZBE_zr_do_st_odH', enumIkon=ico.NavZriadL, dictIkon=ico.dictZriadovacieL, app=parent, comboBox='zriadovacie'),
            25: Navestidlo(ID=25, nazov='Z_Se3p', usekPred='ZBE_Sk', nazovGUI='ZBE_zr_zo_st_odH', enumIkon=ico.NavZriadP, dictIkon=ico.dictZriadovacieP, app=parent, comboBox='zriadovacie'),
            26: Navestidlo(ID=26, nazov='Z_S_fik', usekPred='ZBE_Sk', nazovGUI='ZBE_fik_S', enumIkon=ico.FiktP, dictIkon=ico.dictFiktP, zavisle=66, app=parent, comboBox='fiktivne'),
            27: Navestidlo(ID=27, nazov='Z_S', usekPred='ZBE_HLO_TU1_1', usekZa='ZBE_Sk', nazovGUI='ZBE_S', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, zavisle=67, app=parent, comboBox='vchodove'),
            28: Navestidlo(ID=28, nazov='Z_RAD_ZBE_40', usekPred='RAD_ZBE_TU4', usekZa='RAD_ZBE_TU3', nazovGUI='RAD_ZBE_40', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, app=parent, oddielove=True, TZZ='AB3'),
            29: Navestidlo(ID=29, nazov='Z_RAD_ZBE_39', usekPred='RAD_ZBE_TU3', usekZa='RAD_ZBE_TU4', nazovGUI='RAD_ZBE_39', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, app=parent, oddielove=True, TZZ='AB3'),
            30: Navestidlo(ID=30, nazov='Z_Lo', usekPred='ZBE_HLO_TU1_1', usekZa='ZBE_HLO_TU2_a', nazovGUI='ZBE_HLO_Lo', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=69, app=parent, oddielove=True, TZZ='AH'),
            31: Navestidlo(ID=31, nazov='Z_So', usekPred='ZBE_HLO_TU2_a', usekZa='ZBE_HLO_TU1_1', nazovGUI='ZBE_HLO_So', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, zavisle=70, app=parent, comboBox='oddielove', oddielove=True, TZZ='AH'),
            32: Navestidlo(ID=32, nazov='Z_28_fik', usekPred='RAD_ZBE_TU3', nazovGUI='RAD_ZBE_fik_28', enumIkon=ico.FiktL, dictIkon=ico.dictFiktL, app=parent),
            33: Navestidlo(ID=33, nazov='Z_BS_fik', usekPred='LUZ_ZBE_TU1', nazovGUI='LUZ_fik_BS', enumIkon=ico.FiktL, dictIkon=ico.dictFiktL, app=parent),
            34: Navestidlo(ID=34, nazov='Z_HLO_L_fik', usekPred='ZBE_HLO_TU2_b', nazovGUI='Z_HLO_fikL', enumIkon=ico.FiktP, dictIkon=ico.dictFiktP, app=parent),
            #------------------------------------------HLOHOVEC-----------------------------------------------------------------------------
            35: Navestidlo(ID=35, nazov='H_Se1', usekPred='HLO_Sk', usekZa='HLO_V1', nazovGUI='HLO_zr_do_st_odZ', enumIkon=ico.NavZriadP, dictIkon=ico.dictZriadovacieP, app=parent, comboBox='zriadovacie'),
            36: Navestidlo(ID=36, nazov='H_Se1p', usekPred='HLO_Sk', nazovGUI='HLO_zr_zo_st_odZ', enumIkon=ico.NavZriadL, dictIkon=ico.dictZriadovacieL, app=parent, comboBox='zriadovacie'),
            37: Navestidlo(ID=37, nazov='H_L', usekPred='ZBE_HLO_TU2_b', usekZa='HLO_Sk', nazovGUI='HLO_L', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=71, app=parent, comboBox='vchodove'),
            38: Navestidlo(ID=38, nazov='H_S1', usekPred='HLO_k1', usekZa='HLO_V1', nazovGUI='HLO_S1', enumIkon=ico.NavOdchodL, dictIkon=ico.dictOdchodoveL, zavisle=72, app=parent, comboBox='odchodove'),
            39: Navestidlo(ID=39, nazov='H_S2', usekPred='HLO_k2', usekZa='HLO_V1', nazovGUI='HLO_S2', enumIkon=ico.NavOdchodL, dictIkon=ico.dictOdchodoveL, zavisle=73, app=parent, comboBox='odchodove'),
            40: Navestidlo(ID=40, nazov='H_L_fik', usekPred='HLO_Sk', nazovGUI='HLO_fik_L', enumIkon=ico.FiktL, dictIkon=ico.dictFiktL, zavisle=74, app=parent, comboBox='fiktivne'),
            41: Navestidlo(ID=41, nazov='H_ZBE_L_fik', usekPred='ZBE_HLO_TU1_1', nazovGUI='H_ZBE_fik_S', enumIkon=ico.FiktL, dictIkon=ico.dictFiktL, app=parent),
            42: Navestidlo(ID=42, nazov='H_k1_fik', usekPred='HLO_k1', nazovGUI='HLO_k1_fik', enumIkon=ico.NavOdchodP, dictIkon=ico.dictOdchodoveP, zavisle=76, app=parent, comboBox='odchodove'),
            43: Navestidlo(ID=43, nazov='H_k2_fik', usekPred='HLO_k2', nazovGUI='HLO_k2_fik', enumIkon=ico.NavOdchodP, dictIkon=ico.dictOdchodoveP, zavisle=77, app=parent, comboBox='odchodove'),
            44: Navestidlo(ID=44, nazov='H_Lo', usekPred='H_ZBE_HLO_TU1_1', usekZa='H_ZBE_HLO_TU2_a', nazovGUI='H_ZBE_HLO_Lo', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=69, app=parent, comboBox='oddielove', oddielove=True, TZZ='AH'),
            45: Navestidlo(ID=45, nazov='H_So', usekPred='H_ZBE_HLO_TU2_a', usekZa='H_ZBE_HLO_TU1_1', nazovGUI='H_ZBE_HLO_So', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, zavisle=70, app=parent, oddielove=True, TZZ='AH'),
            #------------------------------------------DISPECER-----------------------------------------------------------------------------
            #------------------------------------------RADOSINA-----------------------------------------------------------------------------
            46: Navestidlo(ID=46, nazov='DR_S', usekPred='DISP_RAD_ZBE_TU1', usekZa='DISP_RAD_Sk', nazovGUI='DISP_RAD_S', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, zavisle=3, app=parent, comboBox='vchodove'),
            47: Navestidlo(ID=47, nazov='DR_L1', usekPred='DISP_RAD_k1', usekZa='DISP_RAD_V1', nazovGUI='DISP_RAD_L1', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=4, app=parent, comboBox='vchodove'),
            48: Navestidlo(ID=48, nazov='DR_L2', usekPred='DISP_RAD_k2', usekZa='DISP_RAD_V1', nazovGUI='DISP_RAD_L2', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=5, app=parent, comboBox='vchodove'),
            49: Navestidlo(ID=49, nazov='DR_S_fik', usekPred='DISP_RAD_Sk', nazovGUI='DISP_RAD_fik_S', enumIkon=ico.FiktP, dictIkon=ico.dictFiktP, zavisle=6, app=parent, comboBox='fiktivne'),
            50: Navestidlo(ID=50, nazov='DR_k1_fik', usekPred='DISP_RAD_k1', nazovGUI='DISP_RAD_k1_fik', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, zavisle=10, app=parent, comboBox='vchodove'),
            51: Navestidlo(ID=51, nazov='DR_k2_fik', usekPred='DISP_RAD_k2', nazovGUI='DISP_RAD_k2_fik', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, zavisle=11, app=parent, comboBox='vchodove'),
            52: Navestidlo(ID=52, nazov='DR_19', usekPred='DISP_RAD_ZBE_TU1', usekZa='DISP_RAD_ZBE_TU2a', nazovGUI='DISP_RAD_ZBE_19', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, app=parent, oddielove=True, TZZ='AB3'),
            53: Navestidlo(ID=53, nazov='DR_18', usekPred='DISP_RAD_ZBE_TU2a', usekZa='DISP_RAD_ZBE_TU1', nazovGUI='DISP_RAD_ZBE_18', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, app=parent, oddielove=True, TZZ='AB3'),
            54: Navestidlo(ID=54, nazov='DR_29', usekPred='DISP_RAD_ZBE_TU2b', usekZa='DISP_RAD_ZBE_TU3', nazovGUI='DISP_RAD_ZBE_29', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, app=parent, oddielove=True, TZZ='AB3'),
            55: Navestidlo(ID=55, nazov='DR_28', usekPred='DISP_RAD_ZBE_TU3', usekZa='DISP_RAD_ZBE_TU2b', nazovGUI='DISP_RAD_ZBE_28', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, app=parent, oddielove=True, TZZ='AB3'),
            #------------------------------------------ZBEHY-----------------------------------------------------------------------------
            56: Navestidlo(ID=56, nazov='DZ_RAD_ZBE_40', usekPred='DISP_RAD_ZBE_TU4', usekZa='DISP_RAD_ZBE_TU3', nazovGUI='DISP_RAD_ZBE_40', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, app=parent, oddielove=True, TZZ='AB3'),
            57: Navestidlo(ID=57, nazov='DZ_RAD_ZBE_39', usekPred='DISP_RAD_ZBE_TU3', usekZa='DISP_RAD_ZBE_TU4', nazovGUI='DISP_RAD_ZBE_39', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, app=parent, oddielove=True, TZZ='AB3'),
            58: Navestidlo(ID=58, nazov='DZ_L', usekPred='DISP_RAD_ZBE_TU4', usekZa='DISP_ZBE_Lk', nazovGUI='DISP_ZBE_L', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=12, app=parent, comboBox='vchodove'),
            59: Navestidlo(ID=59, nazov='DZ_BL', usekPred='DISP_LUZ_ZBE_TU1', usekZa='DISP_ZBE_BLk', nazovGUI='DISP_ZBE_BL', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=13, app=parent, comboBox='vchodove'),
            60: Navestidlo(ID=60, nazov='DZ_L_fik', usekPred='DISP_ZBE_Lk', nazovGUI='DISP_ZBE_fik_L', enumIkon=ico.FiktL, dictIkon=ico.dictFiktL, zavisle=14, app=parent, comboBox='fiktivne'),
            61: Navestidlo(ID=61, nazov='DZ_BL_fik', usekPred='DISP_ZBE_BLk', nazovGUI='DISP_ZBE_fik_BL', enumIkon=ico.FiktL, dictIkon=ico.dictFiktL, zavisle=15, app=parent, comboBox='fiktivne'),
            62: Navestidlo(ID=62, nazov='DZ_S1', usekPred='DISP_ZBE_k1', usekZa='DISP_ZBE_V1', nazovGUI='DISP_ZBE_S1', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, zavisle=20, app=parent, comboBox='vchodove'),
            63: Navestidlo(ID=63, nazov='DZ_S2', usekPred='DISP_ZBE_k2', usekZa='DISP_ZBE_V2', nazovGUI='DISP_ZBE_S2', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, zavisle=21, app=parent, comboBox='vchodove'),
            64: Navestidlo(ID=64, nazov='DZ_L1', usekPred='DISP_ZBE_k1', usekZa='DISP_ZBE_V3', nazovGUI='DISP_ZBE_L1', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=22, app=parent, comboBox='vchodove'),
            65: Navestidlo(ID=65, nazov='DZ_L2', usekPred='DISP_ZBE_k2', usekZa='DISP_ZBE_V3', nazovGUI='DISP_ZBE_L2', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=23, app=parent, comboBox='vchodove'),
            66: Navestidlo(ID=66, nazov='DZ_S_fik', usekPred='DISP_ZBE_Sk', nazovGUI='DISP_ZBE_fik_S', enumIkon=ico.FiktP, dictIkon=ico.dictFiktP, zavisle=26, app=parent, comboBox='fiktivne'),
            67: Navestidlo(ID=67, nazov='DZ_S', usekPred='DISP_ZBE_HLO_TU1_1', usekZa='ZBE_Sk', nazovGUI='DISP_ZBE_S', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, zavisle=27, app=parent, comboBox='vchodove'),
            68: Navestidlo(ID=68, nazov='DZ_BS_fik', usekPred='DISP_LUZ_ZBE_TU1', nazovGUI='DISP_LUZ_fik_BS', enumIkon=ico.FiktL, dictIkon=ico.dictFiktL, app=parent),
            69: Navestidlo(ID=69, nazov='DH_Lo', usekPred='DISP_ZBE_HLO_TU1_4', usekZa='DISP_ZBE_HLO_TU2_a', nazovGUI='DISP_ZBE_HLO_Lo', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=30, app=parent, comboBox='oddielove', oddielove=True, TZZ='AH'),
            #------------------------------------------HLOHOVEC-----------------------------------------------------------------------------
            70: Navestidlo(ID=70, nazov='DH_So', usekPred='DISP_ZBE_HLO_TU2_a', usekZa='DISP_ZBE_HLO_TU1_4', nazovGUI='DISP_ZBE_HLO_So', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, zavisle=45, app=parent, comboBox='oddielove', oddielove=True, TZZ='AH'),
            71: Navestidlo(ID=71, nazov='DH_L', usekPred='DISP_ZBE_HLO_TU2_b', usekZa='DISP_HLO_Sk', nazovGUI='DISP_HLO_L', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=37, app=parent, comboBox='vchodove'),
            72: Navestidlo(ID=72, nazov='DH_S1', usekPred='DISP_HLO_k1', usekZa='DISP_HLO_V1', nazovGUI='DISP_HLO_S1', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, zavisle=38, app=parent, comboBox='vchodove'),
            73: Navestidlo(ID=73, nazov='DH_S2', usekPred='DISP_HLO_k2', usekZa='DISP_HLO_V1', nazovGUI='DISP_HLO_S2', enumIkon=ico.NavVchodL, dictIkon=ico.dictVchodoveL, zavisle=39, app=parent, comboBox='vchodove'),
            74: Navestidlo(ID=74, nazov='DH_L_fik', usekPred='DISP_HLO_Sk', nazovGUI='DISP_HLO_fik_L', enumIkon=ico.FiktL, dictIkon=ico.dictFiktL, zavisle=40, app=parent, comboBox='fiktivne'),
            75: Navestidlo(ID=75, nazov='DH_ZBE_S_fik', usekPred='DISP_ZBE_HLO_TU1_1', nazovGUI='H_ZBE_fik_S', enumIkon=ico.FiktL, dictIkon=ico.dictFiktL, app=parent),
            76: Navestidlo(ID=76, nazov='DH_k1_fik', usekPred='DISP_HLO_k1', nazovGUI='DISP_HLO_k1_fik', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=42, app=parent, comboBox='vchodove'),
            77: Navestidlo(ID=77, nazov='DH_k2_fik', usekPred='DISP_HLO_k2', nazovGUI='DISP_HLO_k2_fik', enumIkon=ico.NavVchodP, dictIkon=ico.dictVchodoveP, zavisle=43, app=parent, comboBox='vchodove'),
        } 